apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test-docker-deploy
  namespace: default
  labels:
    app:  test-docker-deploy
spec:
  selector:
    matchLabels:
      app: test-docker-deploy
  replicas: 2
  template:
    metadata:
      labels:
        app:  test-docker-deploy
    spec:
      containers:
      - name:  test-docker-deploy
        image:  shigoto/test_docker_deploy:latest
        imagePullPolicy: Always
        ports:
        - containerPort:  5000
          name: shigoto 
      restartPolicy: Always
