# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: test-docker-deploy
  namespace: default
spec:
  selector:
    app: test-docker-deploy
  type: NodePort
  ports:
  - name: test-docker-deploy
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30001
